config/routes.rb
Rails.application.routes.draw do
  root 'rss_feeds#index'
  resources :rss_feeds, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rss_feed.rb
class RssFeed < ApplicationRecord
  validates :title, presence: true

  def self.custom
    # validate and get cookies
    validationResponse = RestClient::Request.execute(
      method: :post,
      url: "localhost:8000/signup",
      payload: '{"username" : "user", "password" : "password"}'
    )

    token = validationResponse.cookies

    # get
    response = RestClient::Request.execute(
      method: :post,
      url: "localhost:8000/rss",
      payload: '{"rss_urls" : ["https://news.google.com/rss", "https://www.mediapool.bg/rss"]}',
      cookies: token
    )

    jsonObj = JSON.parse(response)

    # save to db
    jsonObj["items"].each do |feed|
      fd = RssFeed.new(feed)

      if RssFeed.where(:title => fd.title).present?
        print "skipping"
      else
        print "saving"
        fd.save
      end
    end
  end

  def self.search(search)
    if search
      title_type = self.where(title: search)
    else
      @rss_feeds = RssFeed.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
  before_action :set_rss_feed, only: [:show, :edit, :update, :destroy]

  # GET /rss_feeds
  # GET /rss_feeds.json
  def index
    # Background jobs dosnt work so updating it in index
    RssFeed.custom
    # @rss_feeds = RssFeed.all.search(params[:search]).order(publishDate: :desc)
    @rss_feeds = RssFeed.all.order(publishDate: :desc)
  end

  # GET /rss_feeds/1
  # GET /rss_feeds/1.json
  def show
  end

  # GET /rss_feeds/new
  def new
    @rss_feed = RssFeed.new
  end

  # GET /rss_feeds/1/edit
  def edit
  end

  # POST /rss_feeds
  # POST /rss_feeds.json
  def create
    @rss_feed = RssFeed.new(rss_feed_params)

    respond_to do |format|
      if @rss_feed.save
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully created.' }
        format.json { render :show, status: :created, location: @rss_feed }
      else
        format.html { render :new }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rss_feeds/1
  # PATCH/PUT /rss_feeds/1.json
  def update
    respond_to do |format|
      if @rss_feed.update(rss_feed_params)
        format.html { redirect_to @rss_feed, notice: 'Rss feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @rss_feed }
      else
        format.html { render :edit }
        format.json { render json: @rss_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rss_feeds/1
  # DELETE /rss_feeds/1.json
  def destroy
    @rss_feed.destroy
    respond_to do |format|
      format.html { redirect_to rss_feeds_url, notice: 'Rss feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rss_feed
      @rss_feed = RssFeed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rss_feed_params
      params.require(:rss_feed).permit(:title, :source, :sourceURL, :link, :publishDate, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rss_feeds/_form.html.slim
= form_for @rss_feed do |f|
  - if @rss_feed.errors.any?
    #error_explanation
      h2 = "#{pluralize(@rss_feed.errors.count, "error")} prohibited this rss_feed from being saved:"
      ul
        - @rss_feed.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :source
    = f.text_field :source
  .field
    = f.label :sourceURL
    = f.text_field :sourceURL
  .field
    = f.label :link
    = f.text_field :link
  .field
    = f.label :publishDate
    = f.text_field :publishDate
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/rss_feeds/edit.html.slim
h1 Editing rss_feed

== render 'form'

=> link_to 'Show', @rss_feed
'|
=< link_to 'Back', rss_feeds_path

app/views/rss_feeds/index.html.slim
h1 RSS FEED

/ JS dosn't work for some reason ... No idea why
/ Doesn't like $
.container
  .row
    .col-sm-6
      .form-group
        #datetimepicker1.input-group.date
          input.form-control type="text" /
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
    javascript:
      $(function () { $('#datetimepicker1').datetimepicker(); });


/ No clue how to convert from html to slim
/ = form_tag root_path, :method => "get" do
/  = label_tag(:search, "asdasd")
/  = text_field_tag :search, params[:search]
/  = submit_tag "Search"


.list-group
  - @rss_feeds.each do |rss_feed|
    a.list-group-item.list-group-item-action href=rss_feed.link target="_blank" = rss_feed.title
    / a.list-group-item.list-group-item-action = rss_feed.publishDate

app/views/rss_feeds/new.html.slim
h1 New rss_feed

== render 'form'

= link_to 'Back', rss_feeds_path

app/views/rss_feeds/show.html.slim
p#notice = notice

p
  strong Title:
  = @rss_feed.title
p
  strong Source:
  = @rss_feed.source
p
  strong Sourceurl:
  = @rss_feed.sourceURL
p
  strong Link:
  = @rss_feed.link
p
  strong Publishdate:
  = @rss_feed.publishDate
p
  strong Description:
  = @rss_feed.description

=> link_to 'Edit', edit_rss_feed_path(@rss_feed)
'|
=< link_to 'Back', rss_feeds_path